---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: detect-private-key
      - id: no-commit-to-branch
      - id: debug-statements
      - id: name-tests-test
        args: ["--django"]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.3
    hooks:
      - id: bandit
        args: ["-iii", "-ll"] # report only high confidence > medium
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
